Update build_rust_ss_1.23.0.yml

diff --git a/.github/workflows/build_rust_ss_1.23.0.yml b/.github/workflows/build_rust_ss_1.23.0.yml
--- a/.github/workflows/build_rust_ss_1.23.0.yml
+++ b/.github/workflows/build_rust_ss_1.23.0.yml
@@ -25,13 +25,14 @@ jobs:
           prepare: |
             export PKG_PATH=https://ftp.eu.openbsd.org/pub/OpenBSD/7.6/packages/amd64/:https://ftp.openbsd.org/pub/OpenBSD/7.6/packages/amd64/
             pkg_add -u 2>&1 | tee pkg_add_update.log || { echo "Failed to update package index"; cat pkg_add_update.log; exit 1; }
-            pkg_add python py3-setuptools py3-requests gmake git curl cmake bash ggrep gdb libffi ccache ninja rust fish ksh 2>&1 | tee pkg_add_install.log || { echo "Failed to install packages"; cat pkg_add_install.log; pkg_info -Q rust; exit 1; }
+            pkg_add python py3-setuptools py3-requests gmake git curl cmake bash ggrep gdb libffi ccache ninja rust fish  2>&1 | tee pkg_add_install.log || { echo "Failed to install packages"; cat pkg_add_install.log; pkg_info -Q rust; exit 1; }
             ln -sf /usr/local/bin/python3.11 /usr/local/bin/python3
             python3 --version
             rustc --version
             echo "permit nopass root" > /etc/doas.conf
             doas -C /etc/doas.conf && echo "doas configured successfully"
             df -h  # Debug: Check disk space
+            git clone https://github.com/homerouter/pbr
           envs: 'HOME PATH'
 
       - name: Install Rust 1.85 (Beta)
@@ -40,6 +41,7 @@ jobs:
           # Check disk space
           df -h
           # Ensure find-rust-archives.sh is executable
+          cd prb
           ls -l find-rust-archives.sh
           chmod +x find-rust-archives.sh
           # Run script to find beta tarball for December 2024
